# Generated by cpputils-cmake.
include /home/ddovod/_private/_projects/Gestures/build/CMakeFiles/MyGame.dir/flags.make
.PHONY: check-syntax
check-syntax:
	${CXX} -o /dev/null ${CXX_FLAGS} ${CXX_DEFINES}  -S ${CHK_SOURCES}